# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'appprova-ios-poc' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for appprova-ios-poc
  pod 'RxSwift', '~> 3.5.0'
  pod 'RxCocoa', '~> 3.5.0'
  pod 'R.swift', '~> 3.3.0'
  pod 'Swinject', '~> 2.1.0'
  pod 'IQKeyboardManagerSwift', '~> 4.0.10'
  pod 'Alamofire', '~> 4.5.0'

  target 'appprova-ios-pocTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'appprova-ios-pocUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
